config/routes.rb
Rails.application.routes.draw do
  get 'present_community' => 'present_community#index'
  get 'present_community/index'

  root 'welcome#index'

  resources :wifi_devices

  devise_for :users
  resources :communities
  resources :events
  resources :comments
  resources :topics
  resources :services
  resources :parks

  namespace :forum do
    resources :topics do
      collection do 
        get 'index'
      end
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :comments
	belongs_to :communiy
	markable_as :liked
	markable_as :involved_in
end

app/controllers/topics_controller.rb
class TopicsController < WebApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comments = Comment.where(topic: @topic, respond: nil)
    @responses = Comment.where(topic: @topic)
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<% content_for :page_title, 'Topics' %>

<% @topics.each do |topic| %>
  <div class="row">
    <div class="col-sm-12 col-md-10 col-sm-8">
      <div class="box box-success box-solid">
        <div class="box-header with-border"> <%= link_to topic.name, topic_path(topic) %></div>
        <div class="box-body"> <%= topic.description %></div>
      </div>
    </div>
  </div>
<%end%>
  

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class='box box-solid'>
	<div class='box-body'>
		<%= link_to '<i class="fa fa-mail-reply"></i> Back'.html_safe, topics_path, class: 'btn btn-app' %>
		<%= link_to '<i class="fa fa-gear"></i> Edit'.html_safe, edit_topic_path(@topic), class: 'btn btn-app' %>
		<%= link_to '<i class="fa fa-plus"></i> add comment'.html_safe, edit_topic_path(@topic), class: 'btn btn-app' %>
		<%= link_to '<i class="fa fa-remove"></i> Destroy'.html_safe, @topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn bg-maroon btn-app pull-right' %>
		<hr>

		<div class="col-md-12">
			<div class="box box-solid"> 
				<header class="box-header with-border bg-olive" style="height:60px;" id="op5_header" style="color:black">
					<h4><strong>Topic: </strong> <%= @topic.name %> </h4>
				</header>
				<div class="box-body">
					<% @comments.each do |comment|%>
						<div class="row">
							<div class="col-sm-12 col-md-10 col-md-offset-1">
								<div class="box box-solid">
									<div class=" box-header with-border bg-black">
										<%= comment.message %>
									</div>
									<div class="box-body">
										<ul>
											<% @responses.where(respond: comment.id).each do |respond|%>
												<li>
													<%= respond.message %>
												</li>
											<% end %>
										</ul>
									</div>
									<div class="box-footer">
										<%= form_for(Comment.new, html: { class: 'form-horizontal' }) do |f| %>
											<div class="form-group">
												<div class="col-md-9 ">
													<%= f.text_field :message, class: 'form-control' %>
													<%= f.hidden_field :respond,  {value: comment.id, class: 'form-control'} %>
													<%= f.hidden_field :topic_id,  {value: @topic.id, class: 'form-control'} %>
												</div>
												<div class="col-md-3">
													<%= f.submit 'Send', class: 'btn bg-olive btn-block' %>
												</div>
											</div>
										<% end %>
									</div>
								</div>
							</div>
						</div>
					<% end %>					
				</div>
			</div>
		</div>

	</div>
</div>