config/routes.rb
Rails.application.routes.draw do
  get 'present_community' => 'present_community#index'
  get 'present_community/index'

  root 'welcome#index'

  resources :wifi_devices

  devise_for :users
  resources :communities
  resources :events
  resources :comments
  resources :topics
  resources :services
  resources :parks

  namespace :forum do
    resources :topics do
      collection do 
        get 'index'
      end
    end
  end

end

app/models/wifi_device.rb
class WifiDevice < ActiveRecord::Base
  belongs_to :park
end

app/controllers/wifi_devices_controller.rb
class WifiDevicesController < WebApplicationController
  before_action :set_wifi_device, only: [:show, :edit, :update, :destroy]

  # GET /wifi_devices
  # GET /wifi_devices.json
  def index
    @wifi_devices = WifiDevice.all
  end

  # GET /wifi_devices/1
  # GET /wifi_devices/1.json
  def show
  end

  # GET /wifi_devices/new
  def new
    @wifi_device = WifiDevice.new
  end

  # GET /wifi_devices/1/edit
  def edit
  end

  # POST /wifi_devices
  # POST /wifi_devices.json
  def create
    @wifi_device = WifiDevice.new(wifi_device_params)

    respond_to do |format|
      if @wifi_device.save
        format.html { redirect_to @wifi_device, notice: 'Wifi device was successfully created.' }
        format.json { render :show, status: :created, location: @wifi_device }
      else
        format.html { render :new }
        format.json { render json: @wifi_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wifi_devices/1
  # PATCH/PUT /wifi_devices/1.json
  def update
    respond_to do |format|
      if @wifi_device.update(wifi_device_params)
        format.html { redirect_to @wifi_device, notice: 'Wifi device was successfully updated.' }
        format.json { render :show, status: :ok, location: @wifi_device }
      else
        format.html { render :edit }
        format.json { render json: @wifi_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wifi_devices/1
  # DELETE /wifi_devices/1.json
  def destroy
    @wifi_device.destroy
    respond_to do |format|
      format.html { redirect_to wifi_devices_url, notice: 'Wifi device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wifi_device
      @wifi_device = WifiDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wifi_device_params
      params.require(:wifi_device).permit(:park_id, :alerted)
    end
end

app/helpers/wifi_devices_helper.rb
module WifiDevicesHelper
end

app/views/wifi_devices/_form.html.erb
<%= form_for(@wifi_device) do |f| %>
  <% if @wifi_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wifi_device.errors.count, "error") %> prohibited this wifi_device from being saved:</h2>

      <ul>
      <% @wifi_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :park_id %><br>
    <%= f.text_field :park_id %>
  </div>
  <div class="field">
    <%= f.label :alerted %><br>
    <%= f.check_box :alerted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wifi_devices/edit.html.erb
<h1>Editing Wifi Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @wifi_device %> |
<%= link_to 'Back', wifi_devices_path %>

app/views/wifi_devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wifi Devices</h1>

<table>
  <thead>
    <tr>
      <th>Park</th>
      <th>Alerted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wifi_devices.each do |wifi_device| %>
      <tr>
        <td><%= wifi_device.park_id %></td>
        <td><%= wifi_device.alerted %></td>
        <td><%= link_to 'Show', wifi_device %></td>
        <td><%= link_to 'Edit', edit_wifi_device_path(wifi_device) %></td>
        <td><%= link_to 'Destroy', wifi_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wifi device', new_wifi_device_path %>

app/views/wifi_devices/new.html.erb
<h1>New Wifi Device</h1>

<%= render 'form' %>

<%= link_to 'Back', wifi_devices_path %>

app/views/wifi_devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Park:</strong>
  <%= @wifi_device.park_id %>
</p>

<p>
  <strong>Alerted:</strong>
  <%= @wifi_device.alerted %>
</p>

<%= link_to 'Edit', edit_wifi_device_path(@wifi_device) %> |
<%= link_to 'Back', wifi_devices_path %>