config/routes.rb
Rails.application.routes.draw do
  get 'present_community' => 'present_community#index'
  get 'present_community/index'

  root 'welcome#index'

  resources :wifi_devices

  devise_for :users
  resources :communities
  resources :events
  resources :comments
  resources :topics
  resources :services
  resources :parks

  namespace :forum do
    resources :topics do
      collection do 
        get 'index'
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_many :parks
	has_many :topics
	acts_as_marker
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base
	has_many :services
	belongs_to :community
	has_many :wifi_devices
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :comments
	belongs_to :communiy
	markable_as :liked
	markable_as :involved_in
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Markable setup
  acts_as_marker
  has_many :comments

  # Including Gravtastic
  include Gravtastic
  gravtastic
  
end

app/models/wifi_device.rb
class WifiDevice < ActiveRecord::Base
  belongs_to :park
end

app/controllers/events_controller.rb
class EventsController < WebApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date_start, :date_end)
    end
end

app/controllers/parks_controller.rb
class ParksController < WebApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: 'Park was successfully created.' }
        format.json { render :show, status: :created, location: @park }
      else
        format.html { render :new }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: 'Park was successfully updated.' }
        format.json { render :show, status: :ok, location: @park }
      else
        format.html { render :edit }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url, notice: 'Park was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:name, :ubication)
    end
end

app/controllers/topics_controller.rb
class TopicsController < WebApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comments = Comment.where(topic: @topic, respond: nil)
    @responses = Comment.where(topic: @topic)
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wifi_devices_helper.rb
module WifiDevicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenNeighborhood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/partials/_alerts.html.erb
<% if notice or alert %>
	<div class='alert alert-<%= notice ? 'info' : 'warning' %>'>
		<%= notice ? notice : alert %>
		<button class='close' role='button' data-dismiss='alert'>&times;</button>
	</div>
<% end %>

app/views/layouts/partials/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">GreenNeighborhood</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">GN</span>
    <span class="logo-lg">GreenNeighborhood</span>
    
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button" onclick='toggleUserSidebar'>
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
       
        
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header bg-navy">
              <%= image_tag current_user.gravatar_url(default: 'identicon'), class: "img-circle", alt: "User Image" %>
              <p>
                <%= current_user.email %>
              </p>
            </li>
            <!-- Menu Body -->
            <!-- <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li> -->
            <!-- Menu Footer-->
            
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/partials/_main_header.html.erb
<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Green Neighborhood</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Comunidades</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Servicios</a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">Eventos</a>
                </li>
                <li>
                    <a class="page-scroll" href="#team">Foros</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/partials/_main_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
      </div>
      <div class="pull-left info">
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- search form (Optional) -->

    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" style="padding: 0;">
      <li class="header">MENU</li>
      <!-- Optionally, you can add icons to the links -->
      <li class=""><%= link_to "<i class='ion ion-ios-pulse'></i> <span>DIDs</span>".html_safe, communities_path %></li>
      <li class=""><%= link_to "<i class='fa fa-globe'></i> <span>Global DIDs</span>".html_safe, events_path %></li>
      <li class=""><%= link_to "<i class='fa fa-phone'></i> <span>Areas</span>".html_safe, parks_path %></li>
      <li class=""><%= link_to "<i class='fa fa-street-view'></i> <span>Cities</span>".html_safe, services_path %></li>
      <li class=""><%= link_to "<i class='fa fa-university'></i> <span>States</span>".html_safe, topics_path %></li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/web_application.html.erb
!DOCTYPE html>
<html>
	<head>
	  <title>LookingGlass - Administration <%= yield :title %></title>
	  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <!-- Font Awesome Icons -->
	  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	  <!-- Ionicons -->
	  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />

	  <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon" />
		<link rel="apple-touch-icon" href="<%= asset_path 'apple-touch-icon.png' %>" />
		<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'apple-touch-icon-57x57.png' %>" />
		<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'apple-touch-icon-72x72.png' %>" />
		<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'apple-touch-icon-76x76.png' %>" />
		<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'apple-touch-icon-114x114.png' %>" />
		<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'apple-touch-icon-120x120.png' %>" />
		<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'apple-touch-icon-144x144.png' %>" />
		<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'apple-touch-icon-152x152.png' %>" />
	</head>
	<body>
	<%= yield %>
	</body>
</html>

app/views/layouts/webapp.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Green Neighborhood</title>
	  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <!-- Font Awesome Icons -->
	  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	  <!-- Ionicons -->
	  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />

	</head>
	<body class='skin-green-light sidebar-mini'>
		<div class='wrapper'>
			<%= render 'layouts/partials/header' %>
			<%= render 'layouts/partials/main_sidebar' %>
			<div class='content-wrapper'>
				<section class='content-header'>
				</section>
				<section class='content'>
					<%= render 'layouts/partials/alerts' %>
					<%= yield %>
				</section>
			</div>
			<footer class="main-footer">
				<div class="pull-right hidden-xs">
					Green Neighborhood
				</div>
				<strong>Copyright &copy; <%= Date.today.year %> <a href="#">Green</a>.</strong> All rights reserved.
			</footer>
		</div>
	</body>
</html>